### ISSUE TITLE
Custom first day and first week for current week calculation

### ISSUE THREAD

**Issue by Satheeshkumar-Duraisamy** [TomasHubelbauer/vscode-week-number#1]
Can u able to provide an option to configure the following just like Microsoft Outlook to calculate the current number instead of using ISO-8601?
- First day of week
- First week of year

**Comment by TomasHubelbauer** [comment]
Hey, not anytime soon, but you should feel free to adjust the code (the extension is really small and simple) and if you do not want to push a fork to the VS Code extension marketplace, you can distribute your changes as a VSIX. In VS Code, you can install the updated extensions from the VSIX file.

**Comment by Satheeshkumar-Duraisamy** [comment]
I have no idea where to change and how to build and make vsix file.

**Comment by Satheeshkumar-Duraisamy** [comment]
Finally I created vsix file with my changes and installed it as you said. Thanks

**Comment by TomasHubelbauer** [comment]
Feel free to open a PR and whenever I am back to working at this extension I will consider adding an option to switch between the algorithms.
